[WIP] Add PC_RotateQuaternion
LI3DS/pointcloud pull request #29
Opened 2017-01-25 16:12 UTC by elemoine

This PR adds `PC_RotateQuaternion` to rotate patches based on rotation quaternions.

2017-01-25 16:13 UTC, elemoine commented
This is WIP. DO NOT MERGE.

2017-01-25 17:22 UTC, mbredif commented on lib/pc_patch.c
> +        pc_point_get_double_by_name(opt, dimx, &(*vec)[0]);
for performance, you should do the dimx, dimy, dimz lookups only once per patch

2017-01-25 17:25 UTC, mbredif commented on lib/pc_patch.c
> +        pcfree((void *)rotatedvec);
should be freed after the loop

2017-01-25 17:26 UTC, mbredif commented on lib/pc_patch.c
> +    opl = pc_pointlist_from_patch(patch);
can't we modify patch in place ? here, values of other dimensions are left unassigned

2017-01-25 17:28 UTC, mbredif commented on lib/pc_patch.c
> +    const PCMAT44 *qmat;
for a linear rotation, a PCMAT33 and a VEC3 could be used instead

2017-01-25 17:31 UTC, elemoine commented on lib/pc_patch.c
> +    const PCMAT44 *qmat;
Right, will change this.

2017-01-25 17:32 UTC, mbredif commented on lib/pc_matrix.c
> +PCMAT44 *
why do you use a PCMAT44 for a normalized quaternion ? I suggest to use a linear PCMAT33 for a normalized quaternion and a projective PCMAT44 for an unnormalized quaternion, replacing 1's by |q|^2 on the diagonal.

2017-01-25 17:33 UTC, elemoine commented on lib/pc_patch.c
> +    opl = pc_pointlist_from_patch(patch);
`PC_RotateQuaternion` returns a new `PcPatch` so I don't think an in-place modification is possible. Regarding, the other dimensions, I think they should be copied in the new `PcPatch`.

2017-01-25 17:34 UTC, elemoine commented on lib/pc_patch.c
> +        pc_point_get_double_by_name(opt, dimx, &(*vec)[0]);
You mean do a lookup for the very first point and then use indices?

2017-01-25 17:34 UTC, elemoine commented on lib/pc_patch.c
> +        pcfree((void *)rotatedvec);
Right, will change.

2017-01-25 17:36 UTC, elemoine commented on lib/pc_matrix.c
> +PCMAT44 *
As already said, I'll use `PCMAT33` and `PCVEC3` only for this first patch.

2017-01-25 17:43 UTC, mbredif commented on lib/pc_patch.c
> +    opl = pc_pointlist_from_patch(patch);
I think the pointlist is a temporary copy already so that it can be modified in place, but that should be checked obviously.

2017-01-25 17:44 UTC, elemoine commented on lib/pc_patch.c
> +    opl = pc_pointlist_from_patch(patch);
Yep, you may be right. I'll check.

2017-01-25 17:47 UTC, elemoine commented on pgsql/pointcloud.sql.in
> +    RETURNS pcpatchAS 'MODULE_PATHNAME', 'pcpatch_rotate_quaternion'
Missing space before `AS` here.

2017-01-25 17:47 UTC, elemoine commented on lib/pc_patch.c
> +        (*vec)[3] = 0;
To be removed when a 3x3 matrix will be used.

2017-01-25 18:11 UTC, mbredif commented on lib/pc_patch.c
> +        pc_point_get_double_by_name(opt, dimx, &(*vec)[0]);
Yes, I mean `dim = pc_schema_get_dimension_by_name(schema, name);` once then do `pc_point_get_double(pt, dim, d);` for each point.

2017-01-26 10:58 UTC, elemoine commented
@mbredif I addressed your (good) comments.

2017-01-26 17:54 UTC, elemoine commented
@mbredif feel free to review this again.

2017-01-27 13:00 UTC, mbredif commented
Looks good !
2 comments : 
- A comment is needed for future maintainers of the patch version of PC_RotateQuaternion, explaining that points iterated from pointlists extracted from uncompressed patches are just pointers to the raw patch buffer, so that updating the points directly changes the patch payload.
- x and y dimensions should ideally default to the `x_position` and `y_position`. `z_position` is however not provided. I propose to defer that to another issue (https://github.com/LI3DS/pointcloud/issues/32)

2017-01-27 13:34 UTC, elemoine commented
> A comment is needed for future maintainers of the patch version of PC_RotateQuaternion, explaining that points iterated from pointlists extracted from uncompressed patches are just pointers to the raw patch buffer, so that updating the points directly changes the patch payload.

I added a comment.

> x and y dimensions should ideally default to the x_position and y_position. z_position is however not provided. I propose to defer that to another issue

Agree.

2017-01-27 15:08 UTC, elemoine commented
> point rotation through quaternions can be optimized in terms of floating point operations and memory allocation (see : Quaternions_and_spatial_rotation / Used methods 2)

Please be more specific. I don't know undertand what method you're referring to.

2017-01-27 15:30 UTC, elemoine commented
I think I found it. I'll give it a try.

2017-01-27 15:41 UTC, mbredif commented
The most efficient way to rotate a vector with a quaternion is ![{\vec {v}}_{\text{new}}={\vec {v}}+2{\vec {r}}\times ({\vec {r}}\times {\vec {v}}+w{\vec {v}})](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cd7aa3064e12b9321bc210e1e72c7ef488416e7) ([wikipedia](https://en.wikipedia.org/w/index.php?title=Quaternions_and_spatial_rotation&section=26#Performance_comparisons)), which needs 15 multiplications and 15 additions to evaluate (or 18 muls and 12 adds if the factor of 2 is done via multiplication.), compared to the optimal 21 multiplications ( = 12 + 9 ) and 18 add/subtraction ( = 12 + 6 ) with the method of this PR (matrix creation + matrix application).

Considering that the proposed matrix creation method `pc_matrix_create_from_quaternion` is currently not optimized (6 pow, 30 multiplications, 12 add/sub rather than the optimal 0 pow,12 mult,12 add/sub ), I suggest to accept this PR as is and open an issue for this optimization if that becomes a bottleneck, ok?

2017-01-27 16:19 UTC, elemoine commented
I am currently trying to make Method 2 work, but it does not – my unit tests fail. I don't understand why.

2017-01-27 16:23 UTC, elemoine commented
@mbredif please take a look at https://github.com/elemoine/pointcloud/commit/0b6b2e558688d945d481fceb7bfbdac1a31f869d if you have some time. I cannot find what it is not correct and why it doesn't work.

2017-01-27 17:51 UTC, elemoine commented
http://gamedev.stackexchange.com/questions/28395/rotating-vector3-by-a-quaternion is also relevant.

2017-01-27 19:09 UTC, mbredif commented
Thinking back, actually, you construct the matrix once and apply it for each point so its construction cost is amortized and your solution is indeed optimal as soon as you have more than a few points.  The direct quaternion-based rotation ( elemoine@0b6b2e5 ) will thus only be relevant for version where the quaternion changes for each point... Sorry for the confusion.

2017-01-27 20:03 UTC, elemoine commented
> Thinking back, actually, you construct the matrix once and apply it for each point so its construction cost is amortized and your solution is indeed optimal as soon as you have more than a few points. The direct quaternion-based rotation ( elemoine@0b6b2e5 ) will thus only be relevant for version where the quaternion changes for each point... Sorry for the confusion.

Good point. That being said I still don't understand why https://github.com/elemoine/pointcloud/commit/0b6b2e5 doesn't work.

2017-01-27 20:05 UTC, elemoine commented
Before we merge this I'd like to do another change. I think the `pc_patch|point_rotate_quaternion` functions could place `vec` and `rvec` on the stack instead of using `malloc`.

2017-01-27 20:15 UTC, elemoine commented
> Before we merge this I'd like to do another change. I think the pc_patch|point_rotate_quaternion functions could place vec and rvec on the stack instead of using malloc.

Done.

2017-01-28 08:54 UTC, mbredif commented
Could you review mbredif/pointcloud/rotate that enforce const correctness (point rotation is performed in place, which is kind of weird compared to patch rotation which is returning a new patch) and computes rotation matrix on the stack.

2017-01-28 09:57 UTC, elemoine commented
@mbredif https://github.com/mbredif/pointcloud/commit/60cd5c94cd14cc08420e399d7587adb4ba5361c9 in your branch includes many unrelated things.

2017-01-28 13:38 UTC, mbredif commented
My mistake, I cleaned that up in mbredif@a92c265.

2017-01-30 07:58 UTC, elemoine commented
@mbredif I updated the patch based on your commits. This looks good. Thanks for your great suggestions.

2017-01-30 10:04 UTC, mbredif requested changes
Looks good, just a little concern in the comment above.

2017-01-30 10:05 UTC, elemoine commented
> Looks good, just a little concern in the comment above.

What comment?

2017-01-30 10:34 UTC, mbredif commented on pgsql/pc_editor.c
> +    pc_patch_free(patch_out);
only required if patch_in has been cloned or decompressed rather than modified in place

2017-01-30 10:36 UTC, mbredif commented on lib/pc_patch.c
> +    {
My understanding is that you need to pc_patch_uncompressed_clone the patch to ensure that you can modify it.
- going back and forth to a pointlist does not make that logic apparent
- do you really need to clone if the patch is not readonly ? (is the patch readonly in this PR's use case ?)

2017-01-30 10:55 UTC, elemoine commented on lib/pc_patch.c
> +    {
In the case where the input patch is not compressed we could do the rotation in place. But for a consistent API, where the returned patch is alway a new patch, I decided to clone the input patch and do the rotation in that cloned patch.

2017-01-30 10:56 UTC, elemoine commented on pgsql/pc_editor.c
> +    pc_patch_free(patch_out);
As I just commented the output patch is always a new patch. So the user of `pc_patch_rotate_quaternion` is responsible for freeing that output patch.

2017-01-30 11:18 UTC, mbredif commented on lib/pc_patch.c
> +    {
Concerning the api, that pattern is already used in the lib, for instance :
[Conditionnal clone](https://github.com/pgpointcloud/pointcloud/blob/3929653f51296f5dd5fe5997c8c4c5d46419cb50/pgsql/pc_access.c#L578)
[Conditionnal free](https://github.com/pgpointcloud/pointcloud/blob/3929653f51296f5dd5fe5997c8c4c5d46419cb50/pgsql/pc_access.c#L622)

a `pc_patch_uncompressed_clone` function (and its siblings) would enable more readable code and optimized execution.

2017-01-30 11:24 UTC, elemoine commented on lib/pc_patch.c
> +    {
Agree with `pc_patch_uncompressed_clone`, but I did not want to put too much in that patch.

2017-01-30 11:38 UTC, elemoine commented on lib/pc_patch.c
> +    {
> Concerning the api, that pattern is already used in the lib, for instance

So do you mean that my implementation in fine w.r.t. this?

2017-01-30 19:13 UTC, elemoine commented
@mbredif more comments on this PR? Should we merge it?

2017-01-31 08:59 UTC, mbredif approved these changes

2017-01-31 09:19 UTC, merged

2017-01-31 09:31 UTC, mbredif commented
Thanks @elemoine for this PR.
I deferred my little concerns to #38, #39.