Add PC_Affine for patches and points
LI3DS/pointcloud pull request #42
Opened 2017-02-02 15:08 UTC by elemoine

This PR adds `PC_Affine(pcpatch)` and `PC_Affine(pcpoint)` for applying affine transformations to patches and points, respectively.

2017-02-02 16:18 UTC, mbredif requested changes
Sounds good as well. The maths are wrong though

2017-02-02 16:18 UTC, mbredif commented on lib/cunit/cu_pc_point.c
> +    PC_TEST(test_point_affine),
indentation

2017-02-02 16:18 UTC, mbredif commented on lib/pc_api_internal.h
> +typedef double PCVEC4[4];
unused for now

2017-02-02 16:18 UTC, mbredif commented on lib/pc_api_internal.h
> +void pc_matrix_multiply_vector_43(PCVEC3 res, const PCMAT43 mat, const PCVEC4 vec);
vec could be a PCVEC3

2017-02-02 16:18 UTC, mbredif commented on lib/pc_matrix.c
> +}
vec could be a PCVEC3, indexing issues for mat, multiplication by vec[3]==1 should not be performed

2017-02-02 16:22 UTC, elemoine commented on lib/cunit/cu_pc_point.c
> +    PC_TEST(test_point_affine),
My indent is correct. The one for `test_point_hex_inout` and `test_point_access` is not. Fixing the indent in this file should be done with a separate change.

2017-02-02 16:23 UTC, elemoine commented on lib/pc_api_internal.h
> +typedef double PCVEC4[4];
It is used. I need a 4-dimension vector for the 4x3 matrix multiplication.

2017-02-02 16:23 UTC, elemoine commented on lib/pc_api_internal.h
> +void pc_matrix_multiply_vector_43(PCVEC3 res, const PCMAT43 mat, const PCVEC4 vec);
No, I don't think so. It needs to be a 4-dimension vector with the last coordinate set to 1.

2017-02-02 16:25 UTC, elemoine commented
> Sounds good as well. The maths are wrong though

Sorry, I don't understand what's wrong with the math. Please pinpoint the problem. Thanks.

2017-02-02 16:36 UTC, mbredif commented
My mistake, the maths are good. It is just that you can save 3 multiplies by using a PCVEC3 and not multiplying by 1.
`res[2] = mat[8] * vec[0] + mat[9] * vec[1] + mat[10] * vec[2] + mat[11];`
Apart from that, this can be merged.

2017-02-02 17:00 UTC, elemoine commented
> My mistake, the maths are good. It is just that you can save 3 multiplies by using a PCVEC3 and not multiplying by 1.
> res[2] = mat[8] * vec[0] + mat[9] * vec[1] + mat[10] * vec[2] + mat[11];
> Apart from that, this can be merged.

Yep, I'll finish that up tomorrow. Thanks for your reviews.

2017-02-03 09:35 UTC, elemoine commented
Done. I removed `PCVEC4`. Hope this matches to what you had in mind @mbredif.

2017-02-03 19:19 UTC, mbredif approved these changes
Good to go (except the comment issue with PC_RotateTranslate)

2017-02-03 19:19 UTC, mbredif commented on pgsql/pc_editor.c
> +* PC_RotateTranslate(point pcpoint, tx float8, ty float8, tz float8,
PC_RotateTranslate ??

2017-02-03 20:08 UTC, elemoine commented on pgsql/pc_editor.c
> +* PC_RotateTranslate(point pcpoint, tx float8, ty float8, tz float8,
The mistake was there already. I'll fix with a new commit…

2017-02-03 20:10 UTC, elemoine commented
> Good to go (except the comment issue with PC_RotateTranslate)

I added a commit to fix that typo. I was not introduced by this PR's initial commits.

2017-02-03 20:45 UTC, merged

2017-02-03 20:45 UTC, mbredif commented
Thanks @elemoine !