Frustum (WIP)
LI3DS/pointcloud pull request #60
Opened 2017-02-23 10:57 UTC by mbredif

@elemoine, this is a WIP PR to give you quick and dirty preview of the PCFRUSTUM and PCBOX3 architecture and functionalities I have in mind.
Could you please review it and give me feedback about how you could integrate that with your own developments ?

2017-02-24 16:04 UTC, elemoine commented
@mbredif I changed this PR's base branch to `master`. I am in the process of removing `dev` as discussed in https://github.com/LI3DS/pointcloud/issues/55.

2017-02-24 20:15 UTC, elemoine commented on pgsql/pc_editor.c
> +Datum pcpoint_affine(PG_FUNCTION_ARGS);
Oops, I guess I need to create a PR for those missing declarations. At the same time, I wonder why those declarations are needed.

2017-02-24 20:51 UTC, elemoine commented
That's a ton of impressive work! And I must say that it's beyond me right now :) I'd really like to understand what you want to achieve and what problems you aim to solve with this code. Maybe we should have so proper discussion about that.

2017-03-03 14:46 UTC, mbredif commented on pgsql/pc_editor.c
> +Datum pcpoint_affine(PG_FUNCTION_ARGS);
the error I got : 
```
LI3DS/pointcloud/pgsql/pc_editor.c:198:7: warning: no previous prototype for ‘pcpatch_projective’ [-Wmissing-prototypes]
 Datum pcpatch_projective(PG_FUNCTION_ARGS)
       ^
```

2017-03-03 15:34 UTC, elemoine commented on pgsql/pc_editor.c
> +Datum pcpoint_affine(PG_FUNCTION_ARGS);
Could you please help me reproduce the problem? Do you use autotools or cmake? Do you use specific flags? Thanks.

2017-03-03 15:46 UTC, elemoine commented on pgsql/pc_editor.c
> +Datum pcpoint_affine(PG_FUNCTION_ARGS);
Anyway, I created https://github.com/LI3DS/pointcloud/pull/61 for this.

2017-03-03 15:58 UTC, mbredif commented
ok, that is now rebased and more stable, ready for review / merge

2017-03-03 16:03 UTC, elemoine commented
Would be good to remove "WIP" from the first commit.

2017-03-03 16:12 UTC, elemoine requested changes
This looks great! I just made a few minor comments that you might want to consider.

2017-03-03 16:12 UTC, elemoine commented on lib/cunit/cu_pc_frustum.c
> +		for(i=0; i<N; ++i)
I am picky, but could we try respecting the styling used upstream?

```c
for ( mode = 1; mode < 5; ++mode )
{
    for ( i = 0; i < N; ++i)
    {
```

Feel free to reject me if you think I am too pedantic :)

2017-03-03 16:12 UTC, elemoine commented on pgsql/expected/pointcloud.out
> + -127+a/100.0 AS x,
Do you mind removing this change? It's unrelated, and it should be fixed upstream.

2017-03-03 16:12 UTC, elemoine commented on pgsql/pc_editor.c
> +Datum pcpoint_projective(PG_FUNCTION_ARGS);
Please remove this. This is being fixed with a separate PR.

2017-03-03 16:12 UTC, elemoine commented on lib/pc_matrix.c
> +	memcpy(res,mat,16*sizeof(double));
(styling) Spaces are missing.

2017-03-03 16:12 UTC, elemoine commented on lib/pc_matrix.c
> +	memcpy(res,vec,3*sizeof(double));
(styling) Spaces.

2017-03-03 16:33 UTC, mbredif commented on pgsql/expected/pointcloud.out
> + -127+a/100.0 AS x,
ok

2017-03-03 17:10 UTC, mbredif commented
Ok, I took your comments into account.
I propose to squash the commits into 3 more semantic ones so that you can merge them, ok ?
- matrix
- box
- frustum

2017-03-03 17:17 UTC, elemoine commented
Yes, please squash commits as you see fit. Using three commits sounds very good to me. Please tell me if you need help with the squashing/rebasing operations.

2017-03-03 18:26 UTC, mbredif commented
Commits are squashed and tests are passing !
ready to merge

2017-03-07 09:24 UTC, elemoine approved these changes

2017-03-07 09:24 UTC, elemoine commented
Cool, feel free to merge if you think this is ready to go!

2017-03-07 09:25 UTC, merged

2017-03-07 09:25 UTC, elemoine commented
Thank you for the huge work!

2017-03-07 09:26 UTC, mbredif commented
Thanks, your turn now to do the reorganization :)

2017-03-07 09:29 UTC, elemoine commented
I get a lot of warnings with this PR applied. I use the same compilation process and flags as Travis. Can you look into it?

2017-03-07 09:31 UTC, elemoine commented
Tell me if you don't have time, and I'll do it. But I don't want to start the reorg with all these warnings.

2017-03-07 09:58 UTC, mbredif commented
#62 should do it. Feel free to merge or further work on it if you still get warnings.